### ISSUE TITLE
Hourly forecast limited to 348 hours (should be 384)

### ISSUE THREAD

**Issue by ehorvat1** [obones/openhab-binding-openmeteo#2]
Hi, thanks for that OH binding. Its working fine for me, also forcasted time series.

Issue:
I think there is a little typo in the max definition for value "Hours" of "Hourly forcast parameters" . In my opinion it should cover 16 days which makes 384 hours. Actually the maximum limit is at 348 hours....just a little mixup I think.

Please check/modify file "src/main/resources/OH-INF/config/config.xml" at line 46 which is currently:

`<parameter name="hourlyHours" type="integer" groupName="hourlyParameters" min="1" max="348" step="1">`

Thanks again for your time you spent on this.
BR, Bert

**Comment by obones** [comment]
Thanks for the heads up, it is indeed a typo.
This is now fixed in the source and will be present in a future release
